### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by mamefan** [lilyinstarlight/obs-monitor-audio#1]
What do I do about this?

[monitor-audio.py]   File "C:\Users/justi/Downloads\monitor-audio.py", line 109
[monitor-audio.py]     <title>obs-monitor-audio/monitor-audio.py at main · lilyinstarlight/obs-monitor-audio</title>
[monitor-audio.py]                                                       ^
[monitor-audio.py] SyntaxError: invalid character '·' (U+00B7)

**Comment by mamefan** [comment]
[monitor-audio.py] SyntaxError: invalid syntax
[monitor-audio.py]   File "C:\Users/justi/Downloads\monitor-audio.py", line 7
[monitor-audio.py]     <(exclamation point)DOCTYPE html>

**Comment by lilyinstarlight** [comment]
There is no line 109... The file is much shorter than that and also doesn't have `<!DOCTYPE html>` anywhere in the file. Can you check that the contents of it matches what's at <https://github.com/lilyinstarlight/obs-monitor-audio/blob/main/monitor-audio.py>?

**Comment by mamefan** [comment]
I downloaded this https://github.com/lilyinstarlight/obs-monitor-audio/blob/main/monitor-audio.py

I don't know why OBS said that. First time I've tried a plugin like this.

**Comment by lilyinstarlight** [comment]
Yes, can you confirm if the file on your system matches what is in the code at that link? It looks like you got some HTML page instead of the code

**Comment by mamefan** [comment]
If I save as that monitor-audio.py link you put above then open the file in notepad, it has html code in it. I'm attaching it as a zip.
[monitor-audio.zip](https://github.com/lilyinstarlight/obs-monitor-audio/files/15211267/monitor-audio.zip)

**Comment by mamefan** [comment]
I copied your code and pasted it into the file, overwriting everything that was in there, and it works now in OBS. Thanks.

**Comment by lilyinstarlight** [comment]
Glad it's working now! Feel free to open a new issue if you have other problems
